### PR TITLE
27/6/2022

### PR DESCRIPTION
**Pull request by yosef406**
shoe shop is done

### CODE REVIEW

**Comment by yosef406** [comment]
resolved conflicts

**Review by EliasSalom — CHANGES_REQUESTED** [review]
what about semantic comments!! I think you forget about it !!

**Comment by EliasSalom** [comment]
that's not acceptable!!

**Comment by EliasSalom** [comment]
what about semantic comments!! I think you forget about it !! 
that's not acceptable!!
this pull request will be **closed** please provide something better than this brunch name following with an example
=> `feat/OMV-88-dev-ops-add-go-application-to-helm-charts` brunch name
=> `Feat: add go application to helm charts` comment

**Pull request closed without merging**
